USE GD2C2019
GO

-- Verifico si existe el schema, si no existe lo creo

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'GESTION_BDD_2C_2019')
	BEGIN
		EXEC sys.sp_executesql N'CREATE SCHEMA [GESTION_BDD_2C_2019] AUTHORIZATION [gdCupon2019]'
		--PRINT 'Schema correctamente creado'
	END
GO

IF(OBJECT_ID('SP_crear_tablas') IS NOT NULL)
	DROP PROCEDURE SP_crear_tablas

GO
CREATE PROCEDURE SP_CREAR_TABLAS
AS

	BEGIN
		
	IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GESTION_BDD_2C_2019.Rol_Funcionalidad'))
		DROP TABLE GESTION_BDD_2C_2019.Rol_Funcionalidad
	IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GESTION_BDD_2C_2019.Funcionalidad'))
		DROP TABLE GESTION_BDD_2C_2019.Funcionalidad
	IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GESTION_BDD_2C_2019.USUARIO'))
		DROP TABLE GESTION_BDD_2C_2019.USUARIO
	IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'GESTION_BDD_2C_2019.Rol'))
		DROP TABLE GESTION_BDD_2C_2019.Rol

		CREATE TABLE GESTION_BDD_2C_2019.ROL (
		ID NUMERIC(18,0) IDENTITY(1,1) NOT NULL,
		DESCRIPCION NVARCHAR(255) NOT NULL,
		ESTADO BIT NOT NULL DEFAULT 1,
			PRIMARY KEY (ROL_ID)
	);

	CREATE TABLE GESTION_BDD_2C_2019.FUNCIONALIDAD (
		ID NUMERIC(18,0) IDENTITY(1,1)  NOT NULL,
		NOMBRE NVARCHAR(255) NOT NULL,
			PRIMARY KEY (FUNCION_ID)
	)

	CREATE TABLE GESTION_BDD_2C_2019.ROL_FUNCIONALIDAD (
		ID_ROL NUMERIC(18,0) NOT NULL,
		ID_FUNCIONALIDAD NUMERIC(18,0) NOT NULL,
		--	PRIMARY KEY(Rol_Funcionalidad_ID)
	)

	CREATE TABLE GESTION_BDD_2C_2019.USUARIO (
		ID nvarchar(18) PRIMARY KEY NOT NULL,
		TIPO CHAR (2) NOT NULL,
		PASS NVARCHAR(255) NOT NULL,
		ROL NUMERIC (18,0),
		ESTADO TINYINT	NOT NULL DEFAULT 1,
		INTENTOS TINYINT NOT NULL DEFAULT 3,
		)

	END

	
	CREATE TABLE GESTION_BDD_2C_2019.ROL_USUARIO (
		ID_ROL NUMERIC(18,0) NOT NULL,
		ID_USUARIO nvarchar(18) NOT NULL,
	)

		CREATE TABLE GESTION_BDD_2C_2019.CLIENTE (
		ID NUMERIC(18,0) NOT NULL,
		DNI NUMERIC(18) NOT NULL,
		NOMBRE NVARCHAR(255),
		APELLIDO NVARCHAR(255),
		MAIL NVARCHAR(255),
		TELEFONO DATETIME,
		DIRECCION NVARCHAR(255), --FK DIRECCION
		FINANCIAMIENTO NVARCHAR(100),
		USUARIO NVARCHAR(18), --FK USUARIO
		SALDO DECIMAL(18,2)
	)

GO
		EXEC DBO.SP_CREAR_TABLAS
